"""A-share capability catalog, blueprint, and unified data access layer."""

from __future__ import annotations

from .analyst import AStockAnalyst, create_astock_analyst, create_astock_analyst_node
from .blueprint import (
    ASTOCK_BLUEPRINT,
    build_blueprint_markdown,
    build_blueprint_payload,
)
from .data_sources import (
    AStockAdapterBase,
    AStockCachePolicy,
    AStockDataError,
    AStockDataFacade,
    AStockDataRouter,
    AStockNoDataError,
    AStockRequest,
    AStockResponse,
    AStockRouteNote,
    AStockSchemaError,
    AStockSourceUnavailableError,
    AkshareAdapter,
    CninfoAdapter,
    FileAStockCache,
    IwencaiAdapter,
    InMemoryAStockCache,
    MootdxAdapter,
    PROVIDER_ENV_VARS,
    QMTAdapter,
    TencentFinanceAdapter,
    astock_code,
    build_default_adapters,
    normalize_astock_symbol,
    split_astock_symbol,
)
from .interface import AStockInterface, AStockSectionBundle
from .phase9_schemas import (
    PortfolioDecision,
    PortfolioDisposition,
    ResearchConclusion,
    ResearchRecommendation,
    RiskDecision,
    RiskLevel,
    RiskVerdict,
    TraderCandidateAction,
    TraderProposal,
    degraded_research_conclusion,
    degraded_trader_proposal,
)
from .schemas import (  # noqa: F401
    Attribution,
    AuditEvent,
    Fill,
    Order,
    OrderSide,
    OrderStatus,
    OrderTradeMode,
    Portfolio,
    Position,
    Reconciliation,
    ResearchAudit,
    ResearchTask,
    ResearchTaskStatus,
    RiskExposure,
    TaskRun,
    TaskType,
)
from .runtime import (
    AStockGraphReport,
    AStockGraphRuntime,
    BridgeLLM,
    build_astock_research_bridge_state,
    build_astock_runtime_llms,
    is_astock_symbol,
    run_astock_research_bridge,
)
from .runtime_profile import (
    LiveResearchMisconfiguredError,
    RuntimeProfile,
    profile_metadata,
    require_live_research_clients,
    resolve_profile,
)
from .trading_mode import ExecutionCapability, TradingMode
from .execution import (
    BacktestEngine,
    BacktestResult,
    BullTrendStrategy,
    DefensiveMomentumStrategy,
    MeanReversionStrategy,
    MovingAverageTrendStrategy,
    PaperTradeState,
    PaperTrader,
    PutWriteStrategy,
    RSIRangeStrategy,
    RiskGate,
    RiskGateResult,
    StrategyBase,
    ValueAverageStrategy,
)
from .tools import build_astock_tools
from .store import AStockStore, init_astock_db, KlineLoader, ValuationLoader, BatchLoader
from .verification_provenance import (
    VerificationProvenance,
    capture_verification_provenance,
    load_verification_provenance,
    preserve_verification_provenance,
    render_provenance_block,
)

__all__ = [
    "ASTOCK_BLUEPRINT",
    "build_blueprint_markdown",
    "build_blueprint_payload",
    "AStockAdapterBase",
    "AStockCachePolicy",
    "AStockAnalyst",
    "AStockInterface",
    "AStockSectionBundle",
    "AStockGraphReport",
    "AStockGraphRuntime",
    "BridgeLLM",
    "build_astock_research_bridge_state",
    "build_astock_runtime_llms",
    "is_astock_symbol",
    "run_astock_research_bridge",
    "build_astock_tools",
    "create_astock_analyst",
    "create_astock_analyst_node",
    # Verification provenance
    "VerificationProvenance",
    "capture_verification_provenance",
    "load_verification_provenance",
    "preserve_verification_provenance",
    "render_provenance_block",
    # Data-layer errors & adapters
    "AStockDataError",
    "AStockDataFacade",
    "AStockDataRouter",
    "AStockNoDataError",
    "AStockRequest",
    "AStockResponse",
    "AStockRouteNote",
    "AStockSchemaError",
    "AStockSourceUnavailableError",
    "AkshareAdapter",
    "CninfoAdapter",
    "FileAStockCache",
    "IwencaiAdapter",
    "InMemoryAStockCache",
    "MootdxAdapter",
    "PROVIDER_ENV_VARS",
    "QMTAdapter",
    "TencentFinanceAdapter",
    "astock_code",
    "build_default_adapters",
    "normalize_astock_symbol",
    "split_astock_symbol",
    # Phase 09 contract schemas
    "ResearchConclusion",
    "ResearchRecommendation",
    "TraderProposal",
    "TraderCandidateAction",
    "RiskDecision",
    "RiskLevel",
    "RiskVerdict",
    "PortfolioDecision",
    "PortfolioDisposition",
    "degraded_research_conclusion",
    "degraded_trader_proposal",
    # Phase 09 runtime profiles
    "RuntimeProfile",
    "profile_metadata",
    "resolve_profile",
    "require_live_research_clients",
    "LiveResearchMisconfiguredError",
    # Phase 10 execution subpackage
    "StrategyBase",
    "MovingAverageTrendStrategy",
    "BullTrendStrategy",
    "ValueAverageStrategy",
    "MeanReversionStrategy",
    "RSIRangeStrategy",
    "DefensiveMomentumStrategy",
    "PutWriteStrategy",
    "BacktestEngine",
    "BacktestResult",
    "PaperTradeState",
    "PaperTrader",
    "RiskGate",
    "RiskGateResult",
    # Phase 30 trading readiness
    "TradingMode",
    "ExecutionCapability",
    "KillSwitch",
    "kill_switch",
    "RiskReasonCode",
    # Phase 33-37 schemas
    "ResearchTask",
    "ResearchTaskStatus",
    "ResearchAudit",
    "Order",
    "OrderStatus",
    "OrderSide",
    "OrderTradeMode",
    "Fill",
    "Position",
    "Reconciliation",
    "Portfolio",
    "RiskExposure",
    "Attribution",
    "TaskRun",
    "TaskType",
    "AuditEvent",
    "LeaderPoolEntry",
    # Phase 12 DuckDB store
    "AStockStore",
    "init_astock_db",
    "KlineLoader",
    "ValuationLoader",
    "BatchLoader",
]
