"""A-share capability catalog, blueprint, and unified data access layer."""

from .analyst import AStockAnalyst, create_astock_analyst, create_astock_analyst_node
from .blueprint import (
    ASTOCK_BLUEPRINT,
    build_blueprint_markdown,
    build_blueprint_payload,
)
from .data_sources import (
    AStockAdapterBase,
    AStockCachePolicy,
    AStockDataError,
    AStockDataFacade,
    AStockDataRouter,
    AStockNoDataError,
    AStockRequest,
    AStockResponse,
    AStockRouteNote,
    AStockSchemaError,
    AStockSourceUnavailableError,
    AkshareAdapter,
    CninfoAdapter,
    FileAStockCache,
    IwencaiAdapter,
    InMemoryAStockCache,
    MootdxAdapter,
    PROVIDER_ENV_VARS,
    QMTAdapter,
    TencentFinanceAdapter,
    astock_code,
    build_default_adapters,
    normalize_astock_symbol,
    split_astock_symbol,
)
from .interface import AStockInterface, AStockSectionBundle
from .tools import build_astock_tools

__all__ = [
    "ASTOCK_BLUEPRINT",
    "build_blueprint_markdown",
    "build_blueprint_payload",
    "AStockAdapterBase",
    "AStockCachePolicy",
    "AStockAnalyst",
    "AStockInterface",
    "AStockSectionBundle",
    "build_astock_tools",
    "create_astock_analyst",
    "create_astock_analyst_node",
    "AStockDataError",
    "AStockDataFacade",
    "AStockDataRouter",
    "AStockNoDataError",
    "AStockRequest",
    "AStockResponse",
    "AStockRouteNote",
    "AStockSchemaError",
    "AStockSourceUnavailableError",
    "AkshareAdapter",
    "CninfoAdapter",
    "FileAStockCache",
    "IwencaiAdapter",
    "InMemoryAStockCache",
    "MootdxAdapter",
    "PROVIDER_ENV_VARS",
    "QMTAdapter",
    "TencentFinanceAdapter",
    "astock_code",
    "build_default_adapters",
    "normalize_astock_symbol",
    "split_astock_symbol",
]
